### ISSUE TITLE
Exeption при авторизации

### ISSUE THREAD

**Issue by kiselvserg** [GennadyChemyakin/LFC#26]
Вылетает при авторизации с непонятным ексепшеном
![image](https://cloud.githubusercontent.com/assets/1348617/7555750/cc68097c-f75d-11e4-8ffe-908d77c8c65b.png)

**Comment by GennadyChemyakin** [comment]
как часто?

**Comment by kiselvserg** [comment]
Да хз, последнее время чуть ли не через раз
Непонятно в общем

**Comment by kiselvserg** [comment]
Непонятно в общем
